name: Lint

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  tflint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - uses: terraform-linters/setup-tflint@v2
        name: Setup TFLint
        with:
          tflint_version: v0.38.1

  fmt:
    name: Code Format
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:latest
    steps:
      - uses: actions/checkout@v3
      - run: terraform fmt --recursive -check=true

  validate:
    name: Validate
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate Code
        env:
          TF_WARN_OUTPUT_ERRORS: 1
        run: |
          terraform init
          terraform validate
      - name: Validate Examples
        run: |
          for example in $(find examples -maxdepth 1 -mindepth 1 -type d); do
            cd $example
            terraform init
            terraform validate
            cd -
          done
  minimum:
    name: Minimum version check
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:0.13.0
    steps:
      - uses: actions/checkout@master
      - name: Validate Code
        env:
          AWS_REGION: us-east-1
          TF_WARN_OUTPUT_ERRORS: 1
        run: |
          sed -i -e 's/>=/=/' -e 's/ \(\d\+\.\d\+\)"/ \1.0"/' versions.tf
          terraform init
          terraform validate